### PR TITLE
Don't snap links between pins of the same type & Add more info to IsLinkDropped()

### PR DESCRIPTION
**Pull request by Auburns**
I don't think linking pins of the same type is ever a desired behaviour?

### CODE REVIEW

**Comment by Auburns** [comment]
Add more info to IsLinkDropped()

Get the start id of a dropped link and option to ignore detached links

**Comment by Nelarius** [comment]
> I don't think linking pins of the same type is ever a desired behaviour?

Yeah, there's probably no real reason for the library to allow such links since it's a visual error anyway. Good catch!

The code for the additional `IsLinkDropped` info looks like a good inclusion -- just curious, what's the use case you have in mind? 🙂

**Comment by Auburns** [comment]
Here is my use case for the `IsLinkedDropped` info:


Dropping a link will open the context menu for creating a new node, if a new node is created the dropped link will be attached to the new node. It doesn't show the context menu when the dropped link is from a detach, as this is probably not what the user wants.

**Comment by Nelarius** [comment]
Great stuff, thanks! 👌 

In particular, opening the context menu when dragging the link seems great in terms of usability. I'm mainly familiar with Blender's node editor, so I'm missing out on a lot of the usability features from the likes of Unreal and 3ds Max.

**Pull request merged**
