### PR TITLE
draw pin shape with nothing

### PR DESCRIPTION
**Pull request by ketoo**
Sometimes, we don't want to draw any shape for a pin.

### CODE REVIEW

**Comment by ketoo** [comment]
image

**Comment by Nelarius** [comment]
Is there a requirement to be able to link to the "invisible" pin? If not, I usually just leave out the `BeginInputAttribute`/`BeginOutputAttribute` function calls in my node. Here's a (slightly messy) example from my own code:


image

```cpp
const float node_width = 150.f;
imnodes::BeginNode(node.production_fn_node);

imnodes::BeginNodeTitleBar();
ImGui::TextUnformatted("Repeat split");
imnodes::EndNodeTitleBar();

imnodes::BeginInputAttribute(node.predecessor_node);
ImGui::Text("predecessor");
imnodes::EndAttribute();

ImGui::BeginGroup();
{
    // This is the first attribute without a pin! 👇
    // axis_label_widget() just calls ImGui::RadioButton()
    axis_label_widget(
        "dir", grammar.node(node.production_fn_node).body.repeat_split.direction);
}
{
    // And here's the second attribute without a pin 👇
    const float label_width = ImGui::CalcTextSize("count").x;
    ImGui::Text("count");
    ImGui::SameLine();
    ImGui::PushItemWidth(node_width - label_width - 2.f * node_padding);
    ImGui::DragInt(
        "##hidelabel",
        &grammar.node(node.production_fn_node).body.repeat_split.num_splits,
        0.2f, // speed
        1,    // min value
        20);  // max value
    ImGui::PopItemWidth();
}
ImGui::EndGroup();
if (ImGui::IsItemActive())
{
    node_modified = node.production_fn_node;
}

{
    const float label_width = ImGui::CalcTextSize("successors").x;
    imnodes::BeginOutputAttribute(node.successor_nodes[0]);
    ImGui::Indent(node_padding + node_width - label_width);
    ImGui::Text("successors");
    imnodes::EndAttribute();
}

imnodes::EndNode();
```
Note how I added separate handling `if (ImGui::IsItemActive())` logic for the attributes without a pin, in order to detect if they change as well.

This pr skips the rendering of a pin, making the pin effectively invisible, but keeping all the other logic intact. My preference for node attributes without pins would be to just skip the Begin/EndAttribute calls. Would that work for you?

**Comment by ketoo** [comment]
Yes, it can meet the goal if we skip the Begin/EndAttribute calls, but in terms of the concept, it still is a pin and it works with a transparent shape, so "None" is an option of the shape and didn't change the concept of the pin for users. It will break the workflow and break the concept if we skip the Begin/EndAttribute calls, besides, it confuses for users as we have a pin but we don't call Begin/EndAttribute, this is the reason I created this PR.

**Comment by Nelarius** [comment]
My main concern is that the empty pin behavior is also confusing for users:

render_empty_pin_pr

Is the link supposed to attach to an empty pin? Would the user think it is a bug?

But I think you are also right that "pinless" attributes should also be a part of the attribute concept. Imnodes supports the following functions:
```c
bool IsAttributeActive();
bool IsAnyAttributeActive(int* attribute_id = 0);
```
I suppose it would make more sense if you could use these even if you don't want to render a pin.

I would personally implement this with a new "type" of attribute, perhaps something like:
```c
// No pin and thus no link can be attached to the attribute.
BeginUnlinkableAttribute(attribute_id);
EndAttribute();
```
I will keep this pr open for now, and if I can come up with a counterproposal I'm happy with then I will share it here!

**Comment by ketoo** [comment]
I agree with your new idea for the new interface IsAttributeActive and BeginUnlinkableAttribute, it's a good way to avoid the issue and meet the goal!

It shouldn't be linked if a pin is non-active and shouldn't draw the shape.

**Comment by Nelarius** [comment]
*Finally* got around to working on this. The code is in this repo's  `static_attribute` branch. Here's the gist:

```cpp
// Use BeginStaticAttribute/EndStaticAttribute to leave the pin out:
imnodes::BeginStaticAttribute(node.id << 16);
ImGui::PushItemWidth(120.0f);
ImGui::DragFloat("value", &node.value, 0.01f);
ImGui::PopItemWidth();
imnodes::EndStaticAttribute();
```

You now should pair `BeginInputAttribute` with `EndInputAttribute`, and `BeginOutputAttribute` with `EndOutputAttribute`. I left the old `EndAttribute` function in the code for now, but I think I will remove it in the future 🙂 If this sounds like it works, then I will merge the branch! 👍

**Comment by Nelarius** [comment]
I've merged the changes into master -- closing this pr for now 🙂

**Pull request closed without merging**
